# Use the official Go base image
FROM golang:1.19-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application source code to the container
COPY . .

# Set the CGO_ENABLED environment variable to disable CGO
ENV CGO_ENABLED=0

# Run tests and exit
CMD ["go", "test", "-v", "-tags", "integration", "./..."]
