run:
  build-tags:
    - integration

linters-settings:
  goimports:
    # Separate internal packages from external
    local-prefixes: github.com/djurica-surla/golang-exercise

linters:
  # Enable extra linters besides the default ones
  enable:
    - goimports
    - goconst
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - godot
